---
deployment:
  tasks:
    - export REPOPATH=/home/yourdoma/repositories/*
    - export SITEPATH=/home/yourdoma/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH 